"""Core business logic for Mirage.

Adapters (Slack, MCP, APIs) should call into this package instead of
implementing decision-making directly.
"""

from .aliases import (
    STATUS_ALIASES,
    TYPE_ALIASES,
    resolve_status,
    resolve_type,
)
from .calendar import (
    apply_buffer,
    detect_conflicts,
    filter_calendar_fit,
    find_slot,
    protect_morning,
    require_slot,
    safe_get_availability,
    safe_get_week_overview,
    task_fits_calendar,
)
from .config import MirageConfig
from .errors import (
    ConfigError,
    DependencyError,
    MirageCoreError,
    SlottingError,
    ValidationError,
)
from .models import (
    Availability,
    AvailabilityQuery,
    AvailabilityReport,
    AvailabilityWindow,
    DayOverview,
    EnergyLevel,
    IdentityId,
    IdentityProfile,
    IdentityStatement,
    Project,
    ProjectId,
    Review,
    ReviewId,
    Task,
    TaskDraft,
    TaskId,
    TaskMutation,
    TaskStatus,
    TaskType,
    WeekOverview,
    WeekOverviewQuery,
)
from .ports import (
    CalendarPort,
    IdentityRepository,
    ReviewRepository,
    TaskRepository,
)
from .ingestion import CaptureRequest, CaptureResult, IngestionService
from .principles import (
    DecisionFilter,
    PrincipleSection,
    PrinciplesIndex,
    ThinkingMode,
    clear_cache,
    get_principles,
    load_principles,
    parse_principles,
)
from .prioritization import PrioritizationResult, PrioritySuggestion, prioritize
from .services import (
    PROCRASTINATION_THRESHOLD,
    MirageOrchestrator,
    TaskCaptureService,
    filter_actionable,
    flag_procrastinating,
    normalize_task_name,
    sort_by_priority,
)
__all__ = [
    "Availability",
    "AvailabilityQuery",
    "AvailabilityReport",
    "AvailabilityWindow",
    "DayOverview",
    "CalendarPort",
    "apply_buffer",
    "detect_conflicts",
    "filter_calendar_fit",
    "find_slot",
    "protect_morning",
    "require_slot",
    "safe_get_availability",
    "safe_get_week_overview",
    "task_fits_calendar",
    "CaptureRequest",
    "CaptureResult",
    "ConfigError",
    "DependencyError",
    "DecisionFilter",
    "EnergyLevel",
    "IdentityId",
    "IdentityProfile",
    "IdentityRepository",
    "IdentityStatement",
    "IngestionService",
    "MirageConfig",
    "MirageCoreError",
    "MirageOrchestrator",
    "PrinciplesIndex",
    "PROCRASTINATION_THRESHOLD",
    "PrioritizationResult",
    "PrincipleSection",
    "Project",
    "ProjectId",
    "Review",
    "ReviewId",
    "ReviewRepository",
    "SlottingError",
    "STATUS_ALIASES",
    "TYPE_ALIASES",
    "Task",
    "TaskDraft",
    "TaskCaptureService",
    "TaskId",
    "TaskMutation",
    "TaskRepository",
    "TaskStatus",
    "TaskType",
    "PrioritySuggestion",
    "ThinkingMode",
    "ValidationError",
    "WeekOverview",
    "WeekOverviewQuery",
    "clear_cache",
    "get_principles",
    "load_principles",
    "parse_principles",
    "filter_actionable",
    "flag_procrastinating",
    "normalize_task_name",
    "prioritize",
    "resolve_status",
    "resolve_type",
    "sort_by_priority",
]
